[config]
schemaVersion = "0.0.1"

[package]
namespace = "TritonSupreme"
name = "ELT - Network"
versionNumber = "0.1.0"
description = "An extension for ExtraLandscapingTools that add a bunch of network that can be useful for detailing/landscaping your cities."
websiteUrl = "https://github.com/AlphaGaming7780/ELT-Network"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
TritonSupreme-ExtraLandscapingTools = "0.2.1"
TritonSupreme-ELT_SurfaceExtension = "0.1.0"
# AuthorName-PackageName = "0.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods", "tools"]